services:
  mudur:
    build:
      &build
      context: .
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      postgresql:
        condition: service_healthy
      mudur-prerun:
        condition: service_completed_successfully
    env_file:
      &env_file
      - ./.env
    volumes:
      &volumes
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh  # For development purposes only!
      - ./kampyazilim.conf:/app/kampyazilim.conf  # For development purposes only!
      - ./mudur:/app/mudur  # For development purposes only!
      - django_static:/app/mudur/staticfiles  # keep media files secure and ready to be shared with nginx
      - django_media:/app/mudur/media  # keep media files secure and ready to be shared with nginx
      - django_spool_cron:/var/spool/cron  # Remember crontab entries
    restart: on-failure
    healthcheck:
      test:
        [
          "CMD",
          "/usr/bin/curl",
          "--output",
          "/dev/null",
          "--silent",
          "--show-error",
          "--fail",
          "localhost:8080"
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  mudur-prerun:
    build: *build
    env_file: *env_file
    volumes: *volumes
    entrypoint: [ "bash", "-c", "entrypoint.sh managepy migrate && entrypoint.sh managepy collectstatic --noinput && entrypoint.sh managepy compilemessages" ]
    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    image: postgres:13
    tmpfs:
      - /run
      - /var/cache
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    healthcheck:
      test:
        [
          "CMD",
          "psql",
          "--username",
          "${POSTGRES_USER}",
          "--command",
          "SELECT 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"

volumes:
  postgres_data:
  django_static:
  django_media:
  django_spool_cron:
